### ISSUE TITLE
Typo in units.csv and request for times multiplication symbol

### ISSUE THREAD

**Issue by porcaror** [ChHecker/unify#14]
Hi.
Sorry to disturb you.
When I tried to use the coulomb measurement ubit, it didn't work.
I realized, as in the attachement, that there was a typo in the unit.csv file, probabbly it is necessary to remove the character ".
By the way, in LaTeX SIunits, when you type the scientific notation the multiplication sign is a times and not a dot. Could it be possible to have the possibility tto choice between a dot or times symbol also in your package (I attach a file to be clearer).
Thank a lot and sorry for my bad English.
Best regards,
Roberto
[units.csv.pdf](https://github.com/ChHecker/unify/files/13871297/units.csv.pdf)
[Generic.pdf](https://github.com/ChHecker/unify/files/13871299/Generic.pdf)

**Comment by ChHecker** [comment]
Your first remarks was fixed in #8. Thank you for noticing.

As for your feature proposal, that is a good idea. I will look into it myself, but I'm also open to merge requests.

**Comment by ChHecker** [comment]
@RungeCC added an argument to the num etc functions to change the multiplier in #17, e.g.
`$#num("1e9", multiplier: "times")$`.
This addresses your issue sufficiently?
