### ISSUE TITLE
Space before temperature units

### ISSUE THREAD

**Issue by linux-user36** [ChHecker/unify#21]
Typically, the only units you don't use spaces before are a lone-standing degree symbol and primes. This means there _should_ be one if the unit is "°C", "°F" etc., since the "°" has a "suffix" (see e.g. [https://german.stackexchange.com/a/322]).

**Comment by ilyapopov** [comment]
See also paragraph 5.4.3 in [SI Brochure](https://www.bipm.org/documents/20126/41483022/SI-Brochure-9-EN.pdf):

> This rule means that the symbol °C for the degree Celsius is preceded by a space when one expresses values of Celsius temperature t

**Comment by ChHecker** [comment]
That's interesting, I didn't know that. Ergo, add the space before temperature units back, but keep it removed for angles, correct?
