### ISSUE TITLE
Addition of monetary unit

### ISSUE THREAD

**Issue by benjamin-voisin** [ChHecker/unify#26]
I'm not sure if this fits the intended use of this package, but I think having monetary unit it can be usefull (I found this package while writing a financial document, and wanted to unify the typesetting of the numbers I was writing). If that is not in the scope of this package, fine. Else, I can do the PR.

**Comment by ChHecker** [comment]
I see no reason why not to include it. I'd be happy to merge it!
It might make sense to separate it into a different CSV, tho.
