### ISSUE TITLE
Degree and Day has same shorthand

### ISSUE THREAD

**Issue by tedlundwall** [ChHecker/unify#33]
Both Degree and Day has shorthand "d". Degree seems to have priority, making volumetric flow units "m^3/d" unaccessible using shorthand. "meter cubed per day" works but is a hassle. 

Maybe "deg" is suitable as shorthand for degree?

**Comment by ChHecker** [comment]
Thanks for noticing!
Calling degrees `deg` is an immediate fix, the question then is whether to rename Celsius and Fahrenheit, too. On the one hand, `dC` would be inconsistent, on the other hand, it'd be both shorter and backwards compatible.
Either way, as a breaking change, I'll have to give it a thought. Opinions are welcome!
