### ISSUE TITLE
Add a third option to "per" parameter for inline display without negative exponent (example g/cm³)

### ISSUE THREAD

**Issue by idoric** [ChHecker/unify#42]
I would like a third option to the "per" parameter to be able to display units in the form of g/cm³ or km/h.

My use case: I would like to adapt my content to my different audiences by changing its display using a simple `#let qty = qty.with(per: "new third option")`.

**Comment by ChHecker** [comment]
Thanks for the suggestion! Added it in 476a2ae.

**Comment by eltos** [comment]
Multiple units in the denominator are then typically written with multiple slash, e.g. as in

1 Pa = 1 kg/m/s²

**Comment by ChHecker** [comment]
This should be implemented now in 0ae0eb0. Thanks for the proposal!
