### ISSUE TITLE
Leading thin space

### ISSUE THREAD

**Issue by EpicEricEE** [ChHecker/unify#5]
There is an additional thin space at the beginning when using uncertainties, that shouldn't be there:
```typ
#import "@preview/unify:0.4.2": qty, num

#qty("200+-5", "m") \
#num("200+-5")

$(200 plus.minus 5)$ // How it should look
```
![image](https://github.com/ChHecker/unify/assets/7191192/b76b82f1-f2d0-4220-856a-c43981faac26)

_(Using web app, 0.8.0)_

**Comment by ChHecker** [comment]
Nice catch!
The thousands separator was also added in the beginning of the number if it had a multiple of three digits. The newest commit should fix this.
Feel free to reopen if you still notice an issue.
